### ISSUE TITLE
Nothing shown when Atom is up to date

### ISSUE THREAD

**Issue by joshaber** [atom/about#17]
Presumably a regression introduced in https://github.com/atom/about/pull/12.

<img width="560" alt="untitled" src="https://cloud.githubusercontent.com/assets/13760/13867234/69f95daa-ec93-11e5-8065-56c012d01f20.png">

**Comment by as-cii** [comment]
@joshaber: I am not able to reproduce this on `1.7.0-beta0`. Does it happen consistently? 

Since we are not showing any text, maybe we're getting into an "Update State" that we don't have a label for? That might cause [this `switch` statement](https://github.com/atom/about/blob/master/lib/about-view.coffee#L150-L169) to not work properly.

For now, I am going ahead and add an `atom.assert` to validate this hypothesis, so that we can have a report on bugsnag.

**Comment by joshaber** [comment]
>@joshaber: I am not able to reproduce this on 1.7.0-beta0. Does it happen consistently?

Huh, yeah, it does. What does it show for you?
