### ISSUE TITLE
Show more info

### ISSUE THREAD

**Issue by incyi** [atom/about#40]
Show NPM version
Show Node.JS version
Show OS type and version

**Comment by jlvivero** [comment]
Is anyone working on this? I would like to do it, I already did part of it to show that it can be done, still missing npm version and cleaning the code a bit since I was mostly playing with the atom code to get familiar with it. 
Here is the example:
![aboutatom](https://user-images.githubusercontent.com/7948154/30883365-bf773132-a2c0-11e7-80ef-1363c2293378.PNG)

**Comment by damieng** [comment]
I don't think we want to add this functionality to the About dialog. It's easily available from the command line, debug windows etc. and just adds more code to the about package.

**Comment by jlvivero** [comment]
alright, it was a good exercise anyway to get used to atom code so no harm done.

**Comment by damieng** [comment]
And there are plenty more areas you could dive into!  (You did the right thing though and pinged to see if there's still interest before going too far!)
