### ISSUE TITLE
Check now button downloads updates instead of just checking for them

### ISSUE THREAD

**Issue by trych** [atom/about#47]
@lee-dohm

The Check now button in the About window starts to download an available update right away instead of just checking for it and letting the user know if an update is available or not. It does this although the `Automatically download updates` box is unchecked.

While I often like to check if an update is available, I do not always want to download it right away (maybe it's just a minor version, maybe I'm on a slow/unreliable network).

So I think the Check now button should do what it claims to do: check if an update is available and if ask the user if he wants to download it or not. This is how it works in most other software packages.

**Comment by lee-dohm** [comment]
Ok, I understand what you're asking for now. This is partially because of [a limitation in the Electron autoUpdate API](https://github.com/atom/about/pull/12#issuecomment-186761854). We could theoretically work around this limitation to create a flow like this:

1. Click "Check Now"
1. Get notified that there is a new version available or not
1. Change button to "Download" if new version is available
1. Click "Download"
1. Wait for it to download
1. Click "Restart and Install"

But if 80% of the time people are going to want to download a new release if there is one, why make them push the button a third time? And if they are not going to want to download a new version, then does it matter if a new version is available?

For the people that want to only know that there is a new version available, there are options available such as checking https://github.com/atom/atom/releases, subscribing to the [Atom releases RSS feed](https://github.com/atom/atom/releases.atom), watching the [Atom blog](http://blog.atom.io), etc.

**Comment by trych** [comment]
> But if 80% of the time people are going to want to download a new release if there is one, why make them push the button a third time?

Because 20% of people will be annoyed that the download starts, although the button only suggested to check for a new update, not download one. I really commonly do this in software packages, just checking for updates. I want to find out if there are new features, what new features that would be and if it is worth the download.

Also, if a button claims to do a certain thing, it should not do another thing. So an alternative would be to change the button's label. But the default behavior in all other software packages is that you can check for updates and then decide to download, I can think of no good reason why it should be different in Atom.

Btw. at the moment you have to an extra click, when there is _no_ update available. Then a popup window will notify you that there is no update. This should probably also be avoided by just placing the info

```
No update available
Version x.x.x is the latest version.
```

in the box that currently says

```
Atom is up to date!
```

**Comment by Koshmaar** [comment]
> Because 20% of people will be annoyed that the download starts, although the button only suggested to check for a new update, not download one. I really commonly do this in software packages, just checking for updates. I want to find out if there are new features, what new features that would be and if it is worth the download.

Agree, I also do like that. Too many times new updates (in various software) were breaking something.

**Comment by lee-dohm** [comment]
Thanks for the feedback.

We understand the desire for the feature but this isn't something that we feel is going to justify the development effort and ongoing maintenance cost. There are plenty of other ways to check to see if there is a new version, including the [RSS feed for Atom's releases](https://github.com/atom/atom/releases.atom) that could be built as a separate community package. Since this isn't something that the maintainer team intends to work on, I'm going to close it out.

Thanks again for the ideas!

**Comment by ruv** [comment]
For the moment, "Check now" button along with  "Automatically download updates" option  (1) are interpreted as: check for the new version and download it without request if this option is checked, and do not download, if the option is unchecked.

So, yes, the button title should be changed to reflect the behavior. It should be "Check and download now" in place of "Check now".

Also, the option (1) caption should be "Automatically check and download updates", or just "Automatically update" to be more consistent with the message: "Automatic updates are disabled please check manually".

**Comment by trych** [comment]
Thanks @ruv, I also still feel the button is simply mislabled and tbh don't quite understand why this would not be an issue anymore. And yes, the simplest fix would be to simple change the button label as you suggested.
