### ISSUE TITLE
Object.extname is deprecated.

### ISSUE THREAD

**Issue by LuckyChild** [atom/about#61]
Argument to `path.extname` must be a string
```
Object.extname (G:\Atom Beta x64\resources\app\src\electron-shims.js:20:10)
AtomReact.autoSetGrammar (C:\Users\y\.atom\packages\atom-react-0.16.1\lib\atom-react.coffee:162:22)
AtomReact.processEditor (C:\Users\y\.atom\packages\atom-react-0.16.1\lib\atom-react.coffee:361:12)
<unknown> (<embedded>:26088:22)
Function.module.exports.Emitter.simpleDispatch (<embedded>:63204:20)
Emitter.emit (<embedded>:63320:34)
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [react](https://atom.io/packages/react) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
