### ISSUE TITLE
Function.extractParams is deprecated.

### ISSUE THREAD

**Issue by bad4iz** [atom/about#63]
Assigning custom properties to a marker when creating/copying it is
deprecated. Please, consider storing the custom properties you need in
some other object in your package, keyed by the marker's id property.
```
Function.extractParams (<embedded>:118405:20)
MarkerLayer.markRange (<embedded>:72550:77)
TextBuffer.markRange (<embedded>:28244:44)
newMarkers.forEach.marker (C:\Users\bad4i\.atom\packages\livestyle-atom\lib\analyzer\index.js:225:16)
Set.forEach (native)
markBufferWithAnalyzerData (C:\Users\bad4i\.atom\packages\livestyle-atom\lib\analyzer\index.js:224:16)
```

**Comment by 50Wliu** [comment]
Thanks for contributing!

It appears that this is being caused by the [livestyle-atom](https://atom.io/packages/livestyle-atom) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
