### ISSUE TITLE
TextBuffer.setTextInRange is deprecated.

### ISSUE THREAD

**Issue by Eg07** [atom/about#80]
The `undo` option is deprecated. Call groupLastChanges() on the TextBuffer afterward instead.
```
TextBuffer.setTextInRange (<embedded>:33539:22)
TextEditor.setTextInBufferRange (<embedded>:3552:35)
AtomReact.autoCloseTag (C:\Users\Karo\.atom\packages\react\lib\atom-react.coffee:348:27)
<unknown> (C:\Users\Karo\.atom\packages\react\lib\atom-react.coffee:379:24)
Function.module.exports.Emitter.simpleDispatch (<embedded>:66751:20)
Emitter.emit (<embedded>:66880:34)
```

**Comment by Arcanemagus** [comment]
Thanks for contributing!

It appears that this is being caused by the [react](https://github.com/orktes/atom-react) package, not Atom itself. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down. You should file this issue on their repository so they can either fix the problem or tell us where the problem is coming from. The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581).
